config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :articles do 
  	resources :comments
  end
  root 'articles#index'
end  

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord  
  belongs_to :user	
  has_many :comments, :dependent => :delete_all
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @user= current_user
  end

  def show
    @article = Article.find(params[:id])
    @user = current_user
  end
  def my
  	@article= Article.find(current_user.id)
  end	
  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    @article.save()
	  redirect_to @article
  end

  def edit
    @article = Article.find(params[:id])
  end
  	
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/blogs/index.html.erb
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, admin_user_article_path(article.user_id,article.id) %>
    </li>
  <% end %>
</ul>

app/views/articles/edit.html.erb
<h1>New Edit</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<% if !@user %>
  <p><%= link_to "Sign in",new_user_session_path() %></p>	
  <p><%= link_to "Sign up",'users/sign_up' %></p>	
<% end %>
<h1>Articles</h1>
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>
<% if @user %>
	<h1>Create Artcile</h1>
	<p><%= link_to "NEW", new_article_path() %></p>	
	<br>
	<p><%= link_to "Sign out", destroy_user_session_path(), method: :delete %></p>
<% end %>	

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<% if @user %>
<% if @article.user_id == @user.id %>  
  <ul>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>
    <li><%= link_to "Destroy", article_path(@article),method: :delete,data: { confirm: "Are you sure?" } %></li>
  </ul>
<% end %>  
<% end %>
  <h2>Comments</h2>
  <% @article.comments.each do |comment| %>
      <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
      </p>

    <p>
    <strong>Comment:</strong>
    <%= comment.body %>
    </p>
    <% if @user %>
    <% if @article.user_id == @user.id %>  
      <p><%= link_to "Destroy", [comment.article, comment],method: :delete,data: { confirm: "Are you sure?" } %></p>
    <% end %>              
    <% end %>
  <% end %>
<% if @user %>  
  <h2>Add a comment:</h2>
  <%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
<% end %>    

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
 </p>

 <p>
    <strong>Comment:</strong>
    <%= comment.body %>
 </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>